//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcialPedriño.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public int LibroId { get; set; }
        public string titulo { get; set; }
        public string autor { get; set; }
        public Nullable<int> duracion { get; set; }
        public string clasificacion { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        public Nullable<int> CategoriaId { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
